# This is a basic workflow to help you get started with Actions

name: TestCafe workflow

on:[push]

jobs:
  build:
    name: Run TestCafe tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install TestCafe from npm Run TEsts
      - uses: DevExpress/testcafe-action@latest
        with:
        args: "chrome tests"
      

   
